os: linux
node_js: '12'
sudo: required
env: DISPLAY=':99.0'
dist: bionic
language: ruby

rvm:
  - 2.6.3

services:
  - elasticsearch
  - memcached
  - redis-server

addons:
  postgresql: "11"
  apt:
    packages:
      - chromium-browser
      - libgconf-2-4
  chrome: stable

  env:
  global:
  - PGPORT=5433

before_script:
  - sleep 10
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - node --version
  - npm --version
  - yarn install

script:
  - bundle exec rake db:schema:load
  - bundle exec rspec
